import json
from pathlib import Path

from crawl_tools.schema import FullJob

HEADER = '"""Auto-generated by Crawl_Tools. Edit with care."""'

TEMPLATE = '''{header}
# Job: {name}  (run: python {{this file}})
from crawl_tools.loader import job_from_dict
from crawl_tools.runtime.executor import run_job

JOB = {job_dict}

if __name__ == "__main__":
    run_job(job_from_dict(JOB))
'''


def generate_script(job: FullJob) -> str:
    job_dict = json.dumps(job.model_dump(mode="json"), indent=2, ensure_ascii=False)
    return TEMPLATE.format(header=HEADER, name=job.name, job_dict=job_dict)


def write_script(job: FullJob, dest_dir: Path | str = "generated") -> Path:
    dest = Path(dest_dir)
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / f"{job.name}.py"
    path.write_text(generate_script(job), encoding="utf-8")
    return path
