from pathlib import Path

from crawl_tools.compiler.codegen import generate_script, write_script
from crawl_tools.loader import load_and_merge

FIXTURES = Path(__file__).parent / "fixtures"


def _job():
    return load_and_merge(FIXTURES / "job.yaml", platforms_dir=FIXTURES)


def test_generate_script_contains_header_and_job_name():
    src = generate_script(_job())
    assert "Auto-generated by Crawl_Tools" in src
    assert "erp-a-sales" in src
    assert "run_job" in src
    assert "job_from_dict" in src


def test_generated_script_is_valid_python():
    src = generate_script(_job())
    compile(src, "<generated>", "exec")  # 语法合法即不抛异常


def test_generated_script_embeds_steps():
    src = generate_script(_job())
    assert '"action": "login"' in src
    assert '"action": "download"' in src
    assert "${ERP_A_USER}" in src  # 占位符保留,运行时解析(不泄明文)


def test_write_script_creates_file(tmp_path):
    path = write_script(_job(), dest_dir=tmp_path)
    assert path.name == "erp-a-sales.py"
    assert path.exists()
    assert "run_job" in path.read_text(encoding="utf-8")
